# This is a basic workflow that is manually triggered

name: Manual workflow
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "greet"
  docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Check for docker-compose
      run: docker-compose -v
    - name: Check for docker-compose
      run: echo -e "y\ny\ny\n" | ./install.sh
